# Generated by Django 2.2.12 on 2020-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='info',
            field=models.CharField(max_length=200),
        ),
    ]
