# Generated by Django 2.2.12 on 2020-12-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('info', models.CharField(max_length=500, null=True)),
                ('account_type', models.CharField(max_length=30, null=True)),
                ('sub_type', models.CharField(max_length=30, null=True)),
                ('activity', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.AlterField(
            model_name='coamodel',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
