# Generated by Django 2.2.12 on 2020-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201203_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
