# Generated by Django 2.2.12 on 2020-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201206_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.CharField(max_length=30, null=True)),
                ('journal_name', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=500, null=True)),
                ('avail_entities', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'journals',
            },
        ),
    ]
