# Generated by Django 2.2.12 on 2020-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201203_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id',
            name='id_roles',
        ),
        migrations.AddField(
            model_name='id',
            name='id_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='id',
            name='id_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
