# Generated by Django 2.2.12 on 2020-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_journals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=30, null=True)),
                ('rows', models.CharField(max_length=30, null=True)),
                ('year', models.CharField(max_length=30, null=True)),
                ('info', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
    ]
