# Generated by Django 2.2.12 on 2020-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, null=True)),
                ('financial', models.CharField(max_length=30, null=True)),
                ('journals', models.CharField(max_length=30, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'trans_types',
            },
        ),
    ]
